### ISSUE TITLE
Completion callback

### ISSUE THREAD

**Issue by Shadofer** [ZuriPL/svelte-segmented-input#1]
It would be nice if we could assign a callback to be called once every field has been filled out

**Comment by ZuriPL** [comment]
Thanks for the suggestion. I think I will rather handle it with events though

**Comment by Shadofer** [comment]
Also tysm for making this, using it on https://github.com/fronvo/site

**Comment by ZuriPL** [comment]
Hey, thanks for liking my project so much. Even though it's already at 1.x, please treat it as beta software since I only made it  yesterday. You can expect breaking changes up until 2.0 (which I plan on being accessible too) and there are still bugs. 

I'll ship next version in a moment, I just got back home

**Comment by ZuriPL** [comment]
Published as version 1.5.0, including your PR

The event name is `valueEntered`. I will reflect the changes in the documentation tomorrow

Closing the issue now
